name: Update Leaderboard

on:
  push:
    branches:
      - main

jobs:
  update-leaderboard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependency
        uses: sudo pip3 install PyGithub

      - name: Run Script to Update Leaderboard
        run: python3 update_leaderboard.py
